### ISSUE TITLE
AggregateError - Next.js

### ISSUE THREAD

**Issue by mernblockchainlover2019** [rango-exchange/widget-examples#11]
### **Description:**
when i run the widget-example in next.js with yarn, I got the following error.
https://github.com/rango-exchange/widget-examples/tree/main/next
```
- error AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5) {
  code: 'EACCES',
  [errors]: [
    Error: connect EACCES ::1:60839
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -4092,
      code: 'EACCES',
      syscall: 'connect',
      address: '::1',
      port: 60839
    },
    Error: connect ECONNREFUSED 127.0.0.1:60839
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 60839
    }
  ]
}
```

### **Additional Information**
yarn version: 1.22.22
node version: 20.11.1

**Comment by RyukTheCoder** [comment]
The error message you provided indicates a connection issue when running the Next.js widget example. The error codes EACCES and ECONNREFUSED suggest access permission or connection refusal problems. There are a few potential causes for this error:

1. Port conflict: Another process or application may already be using the specified port, causing the connection to be refused. You can try changing the port number in the Next.js project's configuration to a different available port.
2. Firewall or security software: Your firewall or security software might be blocking the connection to the specified IP address and port. Temporarily disabling the firewall or adjusting its settings to allow the connection could resolve the issue.
3. Insufficient privileges: If you're running the project as a non-administrator or non-root user, you may encounter permission-related errors. Ensure that you have sufficient privileges to access the required resources.
